### ISSUE TITLE
Inline Title shows previously opened note title

### ISSUE THREAD

**Issue by mnaoumov** [snezhig/obsidian-front-matter-title#132] opened 2023-06-28 20:16 UTC
If current note doesn't have a `title` key in front matter, Inline Title is shown from the previously opened note

I could not reproduce it for 100%. It comes and goes. Seems like some race condition. Still trying to catch this case

**Comment by MDslash** [comment] 2023-07-04 10:47
+1. Same here. I also can't reproduce it.

**Comment by snezhig** [comment] 2023-07-07 18:54
I found a possible solution. It will be released soon.

**Comment by snezhig** [comment] 2023-07-09 11:57
Should be fixed in [3.4.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.4.0)

**Comment by snezhig** [comment] 2023-07-20 12:48
Feel free to reopen or create a new one.

**Closed by snezhig** 2023-07-20 12:48 UTC
